name: "Publish to PyPI"

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the artifact containing distributions"
        required: false
        default: "release-dists"
        type: string

jobs:
  pypi-publish:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/pacli-tool/
    steps:
      - name: "Download distributions"
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/

      - name: "Publish to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
